### ISSUE TITLE
如何绘制曲线图？ 点击事件有错误（python 3.7版本  mac环境）

### ISSUE THREAD

**Issue by shuaiDevelop** [cumtcdf/RawCoalWashabilityCurve#1]
点击事件错误：AttributeError: 'GridEvent' object has no attribute 'skip'
如何录入数值 绘制出曲线？

**Comment by cumtcdf** [comment]
抱歉,由于图形界面做的比较仓促,人机交互有些别扭.Grid的右击事件里有参考示例.
关于错误的问题,我已经修改.
当然,如果您没有  矿物加工工程  的学科背景, 理解起来可能会有些吃力.
如果您对图形界面感兴趣,可以参考wxPython的官方文档.
[(https://docs.wxpython.org)]
最后,还是感谢您的关注.
